apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-salyards
spec:
  selector:
    matchLabels:
      app: redis-salyards  # has to match .spec.template.metadata.labels
  serviceName: redis-salyards
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-salyards  # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: redis-salyards
          image: redis:7.0.5-alpine
          imagePullPolicy: Always
          args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          # env:
          # - name: REDIS_PASS
          #   valueFrom:
          #     secretKeyRef:
          #       name: redis-secrets-salyards
          #       key: REDIS_PASS
          volumeMounts:
            - name: redis-salyards-volume
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-salyards-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---          
apiVersion: v1
kind: Service
metadata:
  name: redis-salyards
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis-salyards